[build]
command = "npm run build"
functions = "netlify/functions"
publish = "dist"

[env]
[env.production]
  [env.production.environment]
  GEMINI_API_KEY = ""
  GEMINI_MODEL = "gemini-2.5-flash"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[context.production.environment]
GEMINI_API_KEY = ""
GEMINI_MODEL = "gemini-2.5-flash"
